# Generated by Django 5.0.2 on 2024-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_first_name_profile_last_name_profile_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
