# Generated by Django 5.0.2 on 2024-03-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Вид закупки',
                'verbose_name_plural': 'Виды закупок',
                'db_table': 'purchase_type',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=300, unique=True, verbose_name='Номер закупки')),
                ('title', models.CharField(max_length=255, verbose_name='Название закупки')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('date_end', models.DateTimeField(verbose_name='Дата конца')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchasetype', verbose_name='Вид закупки')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'db_table': 'purchase',
            },
        ),
    ]
