# Generated by Django 5.0.2 on 2024-03-02 08:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактные информации',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/legal-act/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Нормативно-правовой акт',
                'verbose_name_plural': 'Нормативно-правовые акты',
                'db_table': 'legal_act',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='files/contract/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='files/documentation/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Документация'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='instruction',
            field=models.FileField(blank=True, null=True, upload_to='files/instruction/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Инструкция'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='tech_task',
            field=models.FileField(blank=True, null=True, upload_to='files/tech_task/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])], verbose_name='Техническое задание'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Победитель'),
        ),
        migrations.CreateModel(
            name='PurchaseAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('requirement', models.CharField(max_length=255, verbose_name='Требования')),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_additional', to='purchase.purchase', verbose_name='Закупка')),
            ],
            options={
                'verbose_name': 'Квалификация и требования',
                'verbose_name_plural': 'Квалификации и требования',
                'db_table': 'purchase_additional',
            },
        ),
    ]
