# Generated by Django 5.0.2 on 2024-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_contactinfo_legalact_purchase_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(max_length=5000, verbose_name='Заголовок'),
        ),
    ]
