# Generated by Django 5.0.2 on 2024-03-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('purchase', '0003_alter_contactinfo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.PositiveBigIntegerField(unique=True, verbose_name='Очередь')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_member', to='account.profile', verbose_name='Профиль')),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_members', to='purchase.purchase', verbose_name='Закупка')),
            ],
        ),
    ]
