# Generated by Django 5.0.2 on 2024-03-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchasemember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasemember',
            options={'verbose_name': 'Участник закупки', 'verbose_name_plural': 'Участники закупки'},
        ),
        migrations.AlterModelTable(
            name='purchasemember',
            table='purchase_members',
        ),
    ]
