# Generated by Django 5.0.2 on 2024-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchasemember_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemember',
            name='status',
            field=models.CharField(blank=True, default='В ожидании', verbose_name='Статус'),
        ),
    ]
